[build]
  command = "npm run build:prod"
  publish = "dist/figma-design-system-generator"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 4200
  publish = "dist/figma-design-system-generator"